package consensus;

public enum ProposalState {	
	PROPOSAL_CONSENSUS,
	PROPOSAL_SUPERSEDED,
	PROPOSAL_PENDING,
	PROPOSAL_SERVICE_FAULT,
	PROPOSAL_ACCESS_DENIAL,
	PROPOSAL_SERVICE_DENIAL,	
	PROPOSAL_CONCURRENT_OPERATION,
	PROPOSAL_NOT_COMMUNICATED,
	PROPOSAL_AGGREGATE_DENIAL
}
