package consensus;

public enum ProposalState {
	
	PROPOSAL_CONSENSUS,
	PROPOSAL_SUPERSEDED,
	PROPOSAL_PENDING,
//	PROPOSAL_REJECTED, // other reason
	PROPOSAL_SERVICE_FAULT,
	PROPOSAL_SERVICE_DENIAL,
	PROPOSAL_CONSISTENCY_FAULT,
	PROPOSAL_NOT_COMMUNICATED

}
