package inputport;

public enum ConnectionType {
	TO_SERVER,
	TO_CLIENT,
	MEMBER_TO_SESSION,
	SERVER_TO_SESSION,
	CLIENT_TO_SESSION,
	TO_PHYSICAL_SERVER,
	TO_LOGICAL_SERVER
//	TO_RELAYER,
//	TO_PEER
}
